apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "nginx.fullname" . }}
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ include "nginx.name" . }}
    helm.sh/chart: {{ include "nginx.chart" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "nginx.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "nginx.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      initContainers:
        - name: code
          image: "{{ .Values.image.code_repository }}:{{ .Chart.Version }}"
          imagePullPolicy: {{ .Values.image.code_pullPolicy }}
          command: ["sh", "-c", "mv /var/web/www /data"]
          volumeMounts:
          - mountPath: /data
            name: code
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          volumeMounts:
          {{- if .Values.vhost }}
            - mountPath: /usr/local/openresty/nginx/conf/vhosts
              name: nginx-vhost-volume
          {{- end }}
          {{- if .Values.nginx }}
            - mountPath: /usr/local/openresty/nginx/conf/nginx.conf
              name: nginx-conf-volume
              subPath: nginx.conf
            {{- toYaml .Values.volumeMounts | nindent 12 }}
          {{- end }}
          readinessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 15
            periodSeconds: 20
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      volumes:
      {{- if .Values.vhost }}
        - name: nginx-vhost-volume
          configMap:
            name: {{ include "nginx.fullname" . }}-vhost.conf
      {{- end }}
      {{- if .Values.nginx }}
        - name: nginx-conf-volume
          configMap:
            name: {{ include "nginx.fullname" . }}-nginx.conf
            items:
            - key: nginx.conf
              path: nginx.conf
        {{- toYaml .Values.volumes | nindent 8 }}
      {{- end }}
    {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
    {{- end }}
    {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
    {{- end }}
