{{- if .Values.vhost -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "nginx.fullname" . }}-vhost.conf
  labels:
    app: {{ include "nginx.fullname" . }}-vhost.conf
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  vhost.conf: |-
{{ .Values.vhost | indent 4 }}
{{- end -}}

