{{- if .Values.phpfpm -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "php.fullname" . }}-php-fpm.conf
  labels:
    app: {{ include "php.fullname" . }}-php-fpm.conf
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
data:
  php-fpm.conf: |-
{{ .Values.phpfpm | indent 4 }}
{{- end -}}
