# Default values for php.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1
namespace: default

image:
  code_repository: 47.244.24.216/code/demo
  code_pullPolicy: IfNotPresent

  repository: 47.244.24.216/library/php
  tag: 7.1.18
  pullPolicy: IfNotPresent

nameOverride: ""
fullnameOverride: ""

service:
  type: ClusterIP
  port: 9000

ingress:
  enabled: false
  annotations: {}
    # kubernetes.io/ingress.class: nginx
    # kubernetes.io/tls-acme: "true"
  paths: []
  hosts:
    - chart-example.local
  tls: []
  #  - secretName: chart-example-tls
  #    hosts:
  #      - chart-example.local

resources: 
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  limits:
    cpu: 200m
    memory: 4Gi
  requests:
    cpu: 100m
    memory: 2Gi

volumeMounts:
  - mountPath: /var/web
    name: code

volumes:
  - name: code
    emptyDir: {}

phpfpm: |-
        [global]
        error_log = /proc/self/fd/2
        log_level = warning
        emergency_restart_threshold = 10
        emergency_restart_interval = 1m
        process_control_timeout = 10s
        daemonize = no

        [www]
        listen = 0.0.0.0:9000
        listen.backlog = 8192
        listen.owner = www
        listen.group = www
        listen.mode = 0666
        user = www
        group = www

        pm = static
        pm.max_children = 21
        pm.max_requests = 102400
        pm.status_path = /php_status

        request_terminate_timeout = 30
        request_slowlog_timeout = 2
        access.log = /proc/self/fd/2
        slowlog = /proc/self/fd/2
        rlimit_files = 65535
        rlimit_core = 0

        catch_workers_output = yes
        env[HOSTNAME] = $HOSTNAME
        env[PATH] = /usr/local/bin:/usr/bin:/bin
        env[TMP] = /tmp
        env[TMPDIR] = /tmp
        env[TEMP] = /tmp

phpini: |-
        [PHP]
        engine = On
        short_open_tag = Off
        precision = 14
        output_buffering = 4096
        zlib.output_compression = Off
        implicit_flush = Off
        unserialize_callback_func =
        serialize_precision = -1
        disable_functions =
        disable_classes =
        zend.enable_gc = On
        expose_php = Off
        max_execution_time = 30
        max_input_time = 60
        memory_limit = 512M
        error_reporting = E_ALL
        display_errors = On
        display_startup_errors = On
        log_errors = On
        log_errors_max_len = 1024
        ignore_repeated_errors = Off
        ignore_repeated_source = Off
        report_memleaks = On
        track_errors = On
        html_errors = On
        variables_order = "GPCS"
        request_order = "GP"
        register_argc_argv = Off
        auto_globals_jit = On
        post_max_size = 150M
        auto_prepend_file =
        auto_append_file =
        default_mimetype = "text/html"
        default_charset = "UTF-8"
        doc_root =
        user_dir =
        enable_dl = Off
        file_uploads = On
        upload_max_filesize = 100M
        max_file_uploads = 500
        allow_url_fopen = On
        allow_url_include = Off
        default_socket_timeout = 60
        [CLI Server]
        cli_server.color = On
        [Date]
        date.timezone = Asia/Shanghai
        [filter]
        [iconv]
        [intl]
        [sqlite3]
        [Pcre]
        [Pdo]
        [Pdo_mysql]
        pdo_mysql.cache_size = 2000
        pdo_mysql.default_socket=
        [Phar]
        [mail function]
        SMTP = localhost
        smtp_port = 25
        mail.add_x_header = Off
        [SQL]
        sql.safe_mode = Off
        [ODBC]
        odbc.allow_persistent = On
        odbc.check_persistent = On
        odbc.max_persistent = -1
        odbc.max_links = -1
        odbc.defaultlrl = 4096
        odbc.defaultbinmode = 1
        [Interbase]
        ibase.allow_persistent = 1
        ibase.max_persistent = -1
        ibase.max_links = -1
        ibase.timestampformat = "%Y-%m-%d %H:%M:%S"
        ibase.dateformat = "%Y-%m-%d"
        ibase.timeformat = "%H:%M:%S"
        [MySQLi]
        mysqli.max_persistent = -1
        mysqli.allow_persistent = On
        mysqli.max_links = -1
        mysqli.cache_size = 2000
        mysqli.default_port = 3306
        mysqli.default_socket =
        mysqli.default_host =
        mysqli.default_user =
        mysqli.default_pw =
        mysqli.reconnect = Off
        [mysqlnd]
        mysqlnd.collect_statistics = On
        mysqlnd.collect_memory_statistics = On
        [OCI8]
        [PostgreSQL]
        pgsql.allow_persistent = On
        pgsql.auto_reset_persistent = Off
        pgsql.max_persistent = -1
        pgsql.max_links = -1
        pgsql.ignore_notice = 0
        pgsql.log_notice = 0
        [bcmath]
        bcmath.scale = 0
        [browscap]
        [Session]
        session.save_handler = files
        session.use_strict_mode = 0
        session.use_cookies = 1
        session.use_only_cookies = 1
        session.name = PHPSESSID
        session.auto_start = 0
        session.cookie_lifetime = 0
        session.cookie_path = /
        session.cookie_domain =
        session.cookie_httponly =
        session.serialize_handler = php
        session.gc_probability = 1
        session.gc_divisor = 1000
        session.gc_maxlifetime = 1440
        session.referer_check =
        session.cache_limiter = nocache
        session.cache_expire = 180
        session.use_trans_sid = 0
        session.sid_length = 26
        session.trans_sid_tags = "a=href,area=href,frame=src,form="
        session.sid_bits_per_character = 5
        [Assertion]
        zend.assertions = 1
        [COM]
        [mbstring]
        [gd]
        [exif]
        [Tidy]
        tidy.clean_output = Off
        [soap]
        soap.wsdl_cache_enabled=1
        soap.wsdl_cache_dir="/tmp"
        soap.wsdl_cache_ttl=86400
        soap.wsdl_cache_limit = 5
        [sysvshm]
        [ldap]
        ldap.max_links = -1
        [mcrypt]
        [dba]
        [opcache]
        opcache.enable=1
        opcache.memory_consumption=512
        opcache.interned_strings_buffer=8
        opcache.max_accelerated_files=4000
        opcache.validate_timestamps=1
        opcache.fast_shutdown=1
        [curl]
        [openssl]
        extension=redis.so
        extension=mongodb.so
        extension=swoole.so
        extension=imagick.so
        extension=xhprof.so
        zend_extension=opcache.so

nodeSelector: {}

tolerations: []

affinity: {}
